//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string CusID { get; set; }
        public byte[] Password { get; set; }
        public string mRank { get; set; }
        public int Point { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
