//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Functions
    {
        public Functions()
        {
            this.Roles = new HashSet<Roles>();
        }
    
        public int FunctionId { get; set; }
        public string FormName { get; set; }
        public string FunctionName { get; set; }
    
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
