//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
        }
    
        public int OrdIntID { get; set; }
        public string OrdID { get; set; }
        public string EmpID { get; set; }
        public string ProID { get; set; }
        public System.DateTime Orddate { get; set; }
        public decimal Total { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
        public virtual Providers Providers { get; set; }
    }
}
